"Vundle install: git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

"--------------------bundle, Vim plugins manager--------------------------
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'https://github.com/VundleVim/Vundle.vim.git'

Plugin 'https://github.com/scrooloose/nerdtree.git'

Plugin 'https://github.com/ctrlpvim/ctrlp.vim.git'
Plugin 'https://github.com/vim-scripts/mru.vim.git'

Plugin 'https://github.com/majutsushi/tagbar.git'
Plugin 'https://github.com/vim-scripts/taglist.vim.git'

Plugin 'https://github.com/scrooloose/syntastic.git'

Plugin 'https://github.com/easymotion/vim-easymotion.git'
" 安装完还需要进入到Youcompleteme的目录编译lib文件，参考https://github.com/Valloric/YouCompleteMe
Plugin 'https://github.com/Valloric/YouCompleteMe.git'
Plugin 'https://github.com/Yggdroot/indentLine.git'

Plugin 'https://github.com/tpope/vim-fugitive.git'
Plugin 'https://github.com/vim-airline/vim-airline.git'
Plugin 'https://github.com/vim-airline/vim-airline-themes.git'

" html
Plugin 'https://github.com/mattn/emmet-vim.git'
Plugin 'https://github.com/gregsexton/MatchTag.git'

" ruby
Plugin 'https://github.com/vim-ruby/vim-ruby.git'
Plugin 'https://github.com/tpope/vim-rails.git'

" scala
Plugin 'https://github.com/derekwyatt/vim-scala.git'

" git plugin
Plugin 'https://github.com/airblade/vim-gitgutter.git'

" Python PEP8 syntax checker, Press <F7> to run flake8 on current file. 
" Plugin 'https://github.com/nvie/vim-flake8.git'  already included in
" syntastic 
Plugin 'https://github.com/davidhalter/jedi-vim.git'

" web development
"Plugin 'https://github.com/Shutnik/jshint2.vim'  " js hint
"Plugin 'https://github.com/skammer/vim-css-color' " css color

call vundle#end()            " required
filetype plugin indent on    " required
"
" Brief help
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
" :PluginUpdate     - update all plugins
"
" Put your non-Plugin stuff after this line
"----------------all above added to use bundle---------------------------


syntax on               " 语法高亮
"colorscheme molokai

set noswapfile

set autoindent
set expandtab           "设置用空格代替Tab, 那么tabstop就没用了，softtabstop决定tabs空格数

set tabstop=4           "Tab键的宽度
set softtabstop=4       "Tab键的宽度
set shiftwidth=4        "默认vim的缩进宽度为8个空格，修改缩进的宽度为4个空格

" associate *.foo with php filetype
au BufRead,BufNewFile *.jst setfiletype html

autocmd Filetype ruby set tabstop=2 | set softtabstop=2 | set shiftwidth=2
autocmd Filetype groovy set tabstop=2 | set softtabstop=2 | set shiftwidth=2
autocmd Filetype html set tabstop=2 | set softtabstop=2 | set shiftwidth=2
autocmd Filetype javascript set tabstop=2 | set softtabstop=2 | set shiftwidth=2

set number              "显示行号
set backspace=indent,eol,start "在insert模式下，启用backspace

set hlsearch            "搜索高亮显示，:/word的搜索
"--------------indent line相关---------------------------------------------
"indentLine 颜色设置
let g:indentLine_color_term = 239    "terminal 中的颜色
let g:indentLine_color_tty_light = 7 "(default: 4)
let g:indentLine_color_dark = 1      "(default: 2)

let g:indentLine_enabled = 1 "默认开启indentLine
let g:indentLine_char = '¦'  "填充字符
"-------------------------------------------------------------------------
"
"auto trigger Pep8 syntax checker while wirting python file.
"autocmd BufWritePost *.py call Flake8()

" Ctrl-n 用来触发nerdtree
map <C-n> :NERDTreeToggle<CR>

" 多Tab页的切换
" 3gt = go to third tab
nnoremap <Tab> gt

" CtrlP setting
let g:ctrlp_map = '<c-p>' " ctrl+f switch to buffer/mru mode

"vim pane switch, useful in tmux mode
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l

" Always show the status line !!!!
set laststatus=2

" vimgrep多文件匹配查找命令，非常强大。 ./**/*中的.是当前工作目录的意思，不是打开的这个文件的位置
map <F3> :execute "vimgrep /" . expand("<cword>") . "/gj ./**/*" <Bar> cw<CR>
" vimgrep /RegEx/gj ./**/*

" 生成C tags文件
map <F12> :!ctags -R .<cr>
" 生成Ruby tags文件
" 1, use 'ripper-tags' (gem install it first), to generate tags file
" 2, Ctrl+] go to definition of method, class, ...
" 3, Ctrl+o backword

" easy motion cfg
nmap s <Plug>(easymotion-s2)

nmap <F8> :TagbarToggle<CR>

nmap <F10> :!ruby %<CR>

" nerdtree忽略的文件过滤器
let NERDTreeIgnore = ['\.pyc$']
let g:nerdtree_tabs_open_on_console_startup=1

" airline
let g:airline_theme = 'powerlineish'
let g:airline#extensions#branch#enabled = 1
"let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#left_sep = ' '
let g:airline#extensions#tabline#left_alt_sep = '|'
let g:airline#extensions#syntastic#enabled = 1
let g:airline#extensions#virtualenv#enabled = 1
let g:airline#extensions#tagbar#enabled = 1

" syntastic settings
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_python_checkers=['flake8']
let g:syntastic_python_flake8_args='--ignore=E501,E225'
let g:syntastic_mode_map = { 'mode': 'active',
                           \ 'passive_filetypes': ['java'] }

" YCM max file size 20 mb
let g:ycm_disable_for_files_larger_than_kb = 20000

" MRU setting
let MRU_Max_Entries = 400
map <leader>f :MRU<CR>

function! GotoJump()
  jumps
  let j = input("Please select your jump: ")
  if j != ''
    let pattern = '\v\c^\+'
    if j =~ pattern
      let j = substitute(j, pattern, '', 'g')
      execute "normal " . j . "\<c-i>"
    else
      execute "normal " . j . "\<c-o>"
    endif
  endif
endfunction
nmap <Leader>j :call GotoJump()<CR>

" 各种命令
" :vertical resize -5 纵向缩小当前window, 5个character的度量
" :resize +5 默认横向扩大window
" normal 模式下，{i}gt, 转到第i个tab页，base1.
